<?php

use Illuminate\Database\Seeder;

class UploadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('uploads')->delete();
        
        \DB::table('uploads')->insert(array (
            0 => 
            array (
                'id' => 1,
                'x' => NULL,
                'y' => NULL,
                'type' => 'image',
                'file_url' => 'https://dizofyq6y2cqx.cloudfront.net/coolaccidents/uploads/573141831f2cc.jpg',
                'original_file_url' => 'https://dizofyq6y2cqx.cloudfront.net/coolaccidents/uploads/573141831f2cc.jpg',
                'name' => NULL,
                'caption' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__5756448c4fc36.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 03:50:39',
                'updated_at' => '2016-06-07 03:50:39',
            ),
            2 => 
            array (
                'id' => 3,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/Screen Shot 2016_06_05 at 3.45.26 PM__575645cdbeea6.png',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 03:56:02',
                'updated_at' => '2016-06-07 03:56:02',
            ),
            3 => 
            array (
                'id' => 4,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__5756465f14bb8.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 03:58:27',
                'updated_at' => '2016-06-07 03:58:27',
            ),
            4 => 
            array (
                'id' => 5,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__575646bf23179.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 04:00:03',
                'updated_at' => '2016-06-07 04:00:03',
            ),
            5 => 
            array (
                'id' => 6,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__57564733f0ffc.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 04:02:01',
                'updated_at' => '2016-06-07 04:02:01',
            ),
            6 => 
            array (
                'id' => 7,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/Screen Shot 2016_06_06 at 10.46.47 AM__57564ae994ede.png',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 04:17:48',
                'updated_at' => '2016-06-07 04:17:48',
            ),
            7 => 
            array (
                'id' => 8,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__57564cd8040ee.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 04:26:04',
                'updated_at' => '2016-06-07 04:26:04',
            ),
            8 => 
            array (
                'id' => 9,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__57564eadd6dbf.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 04:33:53',
                'updated_at' => '2016-06-07 04:33:53',
            ),
            9 => 
            array (
                'id' => 10,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__5756500a4d54e.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 04:39:40',
                'updated_at' => '2016-06-07 04:39:40',
            ),
            10 => 
            array (
                'id' => 11,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__575650e8f3f86.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 04:43:24',
                'updated_at' => '2016-06-07 04:43:24',
            ),
            11 => 
            array (
                'id' => 12,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__575652a0ca540.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 04:50:43',
                'updated_at' => '2016-06-07 04:50:43',
            ),
            12 => 
            array (
                'id' => 13,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__5756530fd8101.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 04:52:36',
                'updated_at' => '2016-06-07 04:52:36',
            ),
            13 => 
            array (
                'id' => 14,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//:files.madeinkatana.com/simon/575126589d310__5756556e16f34.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 05:02:42',
                'updated_at' => '2016-06-07 05:02:42',
            ),
            14 => 
            array (
                'id' => 15,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/575126589d310__575655d0ee651.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 05:04:21',
                'updated_at' => '2016-06-07 05:04:21',
            ),
            15 => 
            array (
                'id' => 16,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/575126589d310__5756569fe5d34.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 05:07:47',
                'updated_at' => '2016-06-07 05:07:47',
            ),
            16 => 
            array (
                'id' => 17,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/575126589d310__5756570636355.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 05:09:30',
                'updated_at' => '2016-06-07 05:09:30',
            ),
            17 => 
            array (
                'id' => 18,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/575126589d310__57565747a04e3.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 05:10:36',
                'updated_at' => '2016-06-07 05:10:36',
            ),
            18 => 
            array (
                'id' => 19,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/575126589d310__575657555404e.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 05:10:49',
                'updated_at' => '2016-06-07 05:10:49',
            ),
            19 => 
            array (
                'id' => 20,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/575126589d310__575657d2284d6.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 05:12:53',
                'updated_at' => '2016-06-07 05:12:53',
            ),
            20 => 
            array (
                'id' => 21,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/Screen Shot 2016_06_07 at 3.02.21 PM__57566690c89c3.png',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 06:16:09',
                'updated_at' => '2016-06-07 06:16:09',
            ),
            21 => 
            array (
                'id' => 22,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/575126589d310__575667d9dee63.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 06:21:22',
                'updated_at' => '2016-06-07 06:21:22',
            ),
            22 => 
            array (
                'id' => 23,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/575126589d310__57566aa49febd.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-07 06:33:14',
                'updated_at' => '2016-06-07 06:33:14',
            ),
            23 => 
            array (
                'id' => 24,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/Screen Shot 2016_06_07 at 3.02.21 PM__575767e282831.png',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-08 00:33:50',
                'updated_at' => '2016-06-08 00:33:50',
            ),
            24 => 
            array (
                'id' => 25,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/Screen Shot 2016_06_07 at 3.00.16 PM__57577a9f5a7be.png',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-08 01:53:41',
                'updated_at' => '2016-06-08 01:53:41',
            ),
            25 => 
            array (
                'id' => 26,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/Screen Shot 2016_06_07 at 3.00.16 PM__57577ce6a260a.png',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-08 02:03:44',
                'updated_at' => '2016-06-08 02:03:44',
            ),
            26 => 
            array (
                'id' => 27,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/Screen Shot 2016_06_07 at 3.02.21 PM__57577fe849611.png',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-08 02:16:15',
                'updated_at' => '2016-06-08 02:16:15',
            ),
            27 => 
            array (
                'id' => 28,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/575126589d310__5757b4ba92611.jpg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-08 15:31:45',
                'updated_at' => '2016-06-08 15:31:45',
            ),
            28 => 
            array (
                'id' => 29,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//files.madeinkatana.com/simon/Screen Shot 2016_05_26 at 1.38.29 PM__5757be6f626ed.png',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-08 16:13:02',
                'updated_at' => '2016-06-08 16:13:02',
            ),
            29 => 
            array (
                'id' => 30,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com//simon/Screen Shot 2016_06_07 at 3.02.21 PM__57635e6127e72.png',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-17 11:50:24',
                'updated_at' => '2016-06-17 11:50:24',
            ),
            30 => 
            array (
                'id' => 31,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/Screen Shot 2016_06_07 at 3.02.21 PM__57635e82c6c09.png',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-06-17 11:50:58',
                'updated_at' => '2016-06-17 11:50:58',
            ),
            31 => 
            array (
                'id' => 32,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57956ffab4d79.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:18:47',
                'updated_at' => '2016-07-25 11:18:47',
            ),
            32 => 
            array (
                'id' => 33,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__579570829c75d.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:21:04',
                'updated_at' => '2016-07-25 11:21:04',
            ),
            33 => 
            array (
                'id' => 34,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__579571c666056.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:26:26',
                'updated_at' => '2016-07-25 11:26:26',
            ),
            34 => 
            array (
                'id' => 35,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957351e5d2a.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:33:03',
                'updated_at' => '2016-07-25 11:33:03',
            ),
            35 => 
            array (
                'id' => 36,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__579574b4a9bc3.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:39:13',
                'updated_at' => '2016-07-25 11:39:13',
            ),
            36 => 
            array (
                'id' => 37,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__579575002b845.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:40:13',
                'updated_at' => '2016-07-25 11:40:13',
            ),
            37 => 
            array (
                'id' => 38,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__5795762195fa9.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:45:01',
                'updated_at' => '2016-07-25 11:45:01',
            ),
            38 => 
            array (
                'id' => 39,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__5795765ec4679.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:46:02',
                'updated_at' => '2016-07-25 11:46:02',
            ),
            39 => 
            array (
                'id' => 40,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__5795772365f15.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:49:21',
                'updated_at' => '2016-07-25 11:49:21',
            ),
            40 => 
            array (
                'id' => 41,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__5795775dc3554.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:50:19',
                'updated_at' => '2016-07-25 11:50:19',
            ),
            41 => 
            array (
                'id' => 42,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__5795778447a24.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:50:58',
                'updated_at' => '2016-07-25 11:50:58',
            ),
            42 => 
            array (
                'id' => 43,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__5795779697ace.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:51:16',
                'updated_at' => '2016-07-25 11:51:16',
            ),
            43 => 
            array (
                'id' => 44,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957822424bc.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:53:35',
                'updated_at' => '2016-07-25 11:53:35',
            ),
            44 => 
            array (
                'id' => 45,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__5795798a576bf.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 11:59:35',
                'updated_at' => '2016-07-25 11:59:35',
            ),
            45 => 
            array (
                'id' => 46,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__579579b4c59d3.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 12:00:18',
                'updated_at' => '2016-07-25 12:00:18',
            ),
            46 => 
            array (
                'id' => 47,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957a25e5fe3.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 12:02:09',
                'updated_at' => '2016-07-25 12:02:09',
            ),
            47 => 
            array (
                'id' => 48,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957aa2b210d.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 12:04:14',
                'updated_at' => '2016-07-25 12:04:14',
            ),
            48 => 
            array (
                'id' => 49,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957b23c3d4c.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 12:06:25',
                'updated_at' => '2016-07-25 12:06:25',
            ),
            49 => 
            array (
                'id' => 50,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957b3ed52b0.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 12:06:52',
                'updated_at' => '2016-07-25 12:06:52',
            ),
            50 => 
            array (
                'id' => 51,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957b6939693.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 12:07:34',
                'updated_at' => '2016-07-25 12:07:34',
            ),
            51 => 
            array (
                'id' => 52,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957cb3a845e.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 12:13:05',
                'updated_at' => '2016-07-25 12:13:05',
            ),
            52 => 
            array (
                'id' => 53,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957f43a38be.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 12:24:00',
                'updated_at' => '2016-07-25 12:24:00',
            ),
            53 => 
            array (
                'id' => 54,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957f5d5b052.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 12:24:27',
                'updated_at' => '2016-07-25 12:24:27',
            ),
            54 => 
            array (
                'id' => 55,
                'x' => NULL,
                'y' => NULL,
                'type' => NULL,
                'file_url' => '//s3.amazonaws.com/files.madeinkatana.com/simon/slack_imgs.com__57957fa674128.jpeg',
                'original_file_url' => NULL,
                'name' => NULL,
                'caption' => NULL,
                'created_at' => '2016-07-25 12:25:39',
                'updated_at' => '2016-07-25 12:25:39',
            ),
        ));
        
        
    }
}
