markdown: kramdown
highlighter: rouge

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

kramdown:
  toc_levels: 2..3
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

sass:
    style: compressed
