title: Soda CMS
tagline: A sweet PHP CMS solution built on Laravel!
github_url: https://github.com/soda-framework/cms
description:
google_analytics_tracking_id:
base_href: http://soda-framework.github.io/cms
favicon: assets/favicon.ico
apple_touch:
logo:
