<?php

return [
    'checkbox'           => Soda\Cms\FrontendBuilder\Forms\Fields\Checkbox::class,
    'radio'              => Soda\Cms\FrontendBuilder\Forms\Fields\Radio::class,
    'code'               => Soda\Cms\FrontendBuilder\Forms\Fields\Code::class,
    'combobox'           => Soda\Cms\FrontendBuilder\Forms\Fields\Combobox::class,
    'datetime'           => Soda\Cms\FrontendBuilder\Forms\Fields\Datetime::class,
    'dropdown'           => Soda\Cms\FrontendBuilder\Forms\Fields\Dropdown::class,
    'fancy_upload'       => Soda\Cms\FrontendBuilder\Forms\Fields\FancyUpload::class,
    'json'               => Soda\Cms\FrontendBuilder\Forms\Fields\Json::class,
    'multiselect'        => Soda\Cms\FrontendBuilder\Forms\Fields\Multiselect::class,
    'password'           => Soda\Cms\FrontendBuilder\Forms\Fields\Password::class,
    'static_text'        => Soda\Cms\FrontendBuilder\Forms\Fields\StaticText::class,
    'static_image'       => Soda\Cms\FrontendBuilder\Forms\Fields\StaticImage::class,
    'hidden'             => Soda\Cms\FrontendBuilder\Forms\Fields\Hidden::class,
    'relationship'       => Soda\Cms\FrontendBuilder\Forms\Fields\Relationship::class,
    'relationship_group' => Soda\Cms\FrontendBuilder\Forms\Fields\RelationshipGroup::class,
    'tags'               => Soda\Cms\FrontendBuilder\Forms\Fields\Tags::class,
    'text'               => Soda\Cms\FrontendBuilder\Forms\Fields\Text::class,
    'textarea'           => Soda\Cms\FrontendBuilder\Forms\Fields\Textarea::class,
    'tinymce'            => Soda\Cms\FrontendBuilder\Forms\Fields\Tinymce::class,
    'toggle'             => Soda\Cms\FrontendBuilder\Forms\Fields\Toggle::class,
    'slug'               => Soda\Cms\FrontendBuilder\Forms\Fields\Slug::class,
    'upload'             => Soda\Cms\FrontendBuilder\Forms\Fields\Upload::class,
];
